# Generated by Django 2.2.7 on 2019-11-05 23:03

import datetime
from django.db import migrations
from django.utils.timezone import utc
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspot',
            name='coord',
            field=djgeojson.fields.PointField(default=datetime.datetime(2019, 11, 5, 23, 3, 44, 956011, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
